require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/MethodDefParentheses:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20 # Probably way too high but unsure where the cutoff should be. The default was too low.

Metrics/PerceivedComplexity:
  Max: 20 # Probably way too high but unsure where the cutoff should be. The default was too low.

Style/Documentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# Although I generally agree that these are a bad practice, we're making an exception in order
# to create a DSL
Style/ClassVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false
  
Metrics/ParameterLists:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

# This may be a bug in rubocop. It recommends things that actually change the behaviour.
Lint/NonAtomicFileOperation:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
  
Performance/ChainArrayAllocation:
  Enabled: false